/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;


import javax.imageio.ImageIO;
import javax.swing.JFrame;

/**
 *
 * @author ch
 */
public class Mensagem extends AbstractJFrame {
   
    /**
     * Create new form Mensagem
     * @param ant ponteiro pra tela anterior
     * @param msgInfo mensagem adicional que pode ser inserida na mensagem em caso
     *                de falha na operação. Pode ser null.
     * @param status pode ser SUCCESS ou FAIL. 
     * @param tipo pode ser CADASTRO, ATUALIZACAO ou REMOCAO
     */  
    public Mensagem(JFrame ant, String msgInfo, int status, int tipo){
        super(ant);
        initComponents();
        
        // Mostra a msg de acordo com seu tipo:
        String msg = null;
        switch(tipo){
            case CADASTRO:
            {
                if(status == SUCCESS) {
                    msg = new String("Cadastrado realizado com sucesso!");
                } else {    
                    msg = new String("Não foi possível realizar o cadastro.\n");
                    if (msgInfo != null)
                        msg += "Descrição: "+msgInfo;
                }
                break;
            }
            case ATUALIZACAO:
            {
                if(status == SUCCESS) {
                    msg = new String("Atualização realizada com sucesso!");
                } else {    
                    msg = new String("Não foi possível realizar atualização nos dados.\n");
                    if (msgInfo != null)
                        msg += "Descrição: "+msgInfo;
                }
                break;
            }
            case REMOCAO:
            {
                if(status == SUCCESS) {
                    msg = new String("Remoção realizada com sucesso!");
                } else {    
                    msg = new String("Não foi possível realizar a remoção dos dados.\n");
                    if (msgInfo != null)
                        msg += "Descrição: "+msgInfo;
                }
                break;
            }
        }
        if(msg != null)
            msgLabel.setText(msg);
    }

    private Mensagem() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        msgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info.png"))); // NOI18N

        msgLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mensagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mensagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel msgLabel;
    // End of variables declaration//GEN-END:variables
}
